version: '3.8'
services:
  app:
    build: ./
    restart: always
    ports:
      - 3001:3001
    env_file: ./.env
    depends_on:
      - mongo
    volumes:
      - ./:/app
    command: npm run start:production
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
