version: '3'

services:
  application:
    build: ./
    container_name: personal-backend
    expose:
      - 3001
    depends_on:
      - mongo
    volumes:
      - ./:/app
    command: npm run start

  database:
    image: mongo
    container_name: personal-backend-database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  proxy:
    external:
      name: nginx-proxy
