version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: personal-backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: ./
    ports:
      - 3001:3001
    depends_on:
      - postgres
    volumes:
      - ./:/app
    command: npm run start
volumes:
  postgres-data:
